## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.5
  - nightly
notifications:
  email: false
git:
  depth: 99999999
matrix:
  allow_failures:
    - julia: nightly
    - julia: 1.0
    - os: windows

# PDF and SVG export
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pdf2svg
  - sudo apt-get install -y texlive-latex-base
  - sudo apt-get install -y texlive-binaries
  - sudo apt-get install -y texlive-pictures
  - sudo apt-get install -y texlive-latex-extra

# push coverage results to Codecov
after_success:
  - julia -e 'cd(Pkg.dir("CriticalDifferenceDiagrams")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
