## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
sudo: required
dist: trusty
julia:
  - 1.0
  - 1.5
  - nightly
notifications:
  email: false
git:
  depth: 99999999
jobs:
  allow_failures:
    - julia: nightly
    - os: windows
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

# PDF and SVG export (only on linux)
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get -qq update ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get install -y pdf2svg texlive-latex-base texlive-binaries texlive-pictures texlive-latex-extra ; fi

# push coverage results to Codecov
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("CriticalDifferenceDiagrams")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
