name = "CriticalDifferenceDiagrams"
uuid = "e3dcb5d8-23d5-4a0a-a175-b3f280ae1849"
authors = ["Mirko Bunse <mirko.bunse@cs.tu-dortmund.de>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
